version: '3.8'

services:
    app:
        image: 'php:8.2-fpm-alpine'
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel
    web:
        image: 'nginx:latest'
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel
    mysql:
        image: 'mysql:8'
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - laravel
    redis:
        image: 'redis:latest'
        networks:
            - laravel
    worker:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel
networks:
    laravel:

